### PR TITLE
Add option to fix banner crc

### PR DESCRIPTION
**Pull request by Lorenzooone**
Adds ability to fix the banner CRC. It does not fully handle https://github.com/blocksds/ndstool/issues/1 , but it can help, and it's a start.

### CODE REVIEW

**Comment by asiekierka** [comment]
Why is this necessary, if you can provide your own (presumably correct) banner.bin?

**Comment by Lorenzooone** [comment]
I wouldn't call it necessary. But just like the option to fix the header crc is there, this can be useful. It's more of an helper function which can be used by users. A "dual" of the other function.

**Comment by asiekierka** [comment]
I see

**Comment by Lorenzooone** [comment]
Do not merge in until #3 is merged in.
Will need to "Improve it" with #3 's changes for CRCs and all.

**Comment by AntonioND** [comment]
@Lorenzooone #3 is merged, you can update this PR now.

**Comment by Lorenzooone** [comment]
@AntonioND ready for review!

**Comment by asiekierka** [comment]
Looks good to me

**Pull request merged**
